---
title: "Map of beaver locations on the Kern Plateau, California"
author: "<strong>Roland A. Knapp</strong> <br>email: roland.knapp@ucsb.edu <br> GitHub: <https://github.com/rolandknapp/beaver_map>"
date: "`r format(Sys.time())`"
format: html
editor: visual
---

```{r, echo=FALSE, message=FALSE}
library(leaflet)
library(readr)
library(dplyr)
```

```{r, echo=FALSE, message=FALSE}
beaver_info <- read_csv("./data/beaver_locations.csv") %>% 
  filter(!is.na(lat)) %>% 
  select(-photo, -photo_14Csample, -date_14C)
```

```{r, echo=FALSE}
leaflet(beaver_info, 
        width = 500, 
        height = 500,
        options = leafletOptions(minZoom = 11)) %>% 
setView(lng = -118.2055, 
          lat = 36.3173, 
          zoom = 11) %>% 
setMaxBounds(lng1 = -118.4743, 
             lat1 = 36.5500,
             lng2 = -117.9657, 
             lat2 = 36.1450) %>% 
  addProviderTiles(providers$OpenTopoMap) %>% 
  addMarkers(
      lng = ~lon,
      lat = ~lat, 
      popup = paste0(
      "<strong>Site name: </strong>", beaver_info$site_name, "<br>",
      "<strong>Activity: </strong>", beaver_info$activity, "<br>",
      "<strong>Observer: </strong>", beaver_info$observer, "<br>",
      "<strong>Date: </strong>", beaver_info$date, "<br>",
      "<strong>Current status: </strong>", beaver_info$status, "<br>",
      "<strong>Notes: </strong>", beaver_info$notes))
```
